/* ---------------------------------
   CRIANDO AS TABELAS
   --------------------------------- */

-- Conectar com o usuário FOLHA
CREATE TABLE T_DEPARTAMENTO
(
 COD_DEPTO             NUMBER(2),
 NOM_DEPTO             VARCHAR2(30),
 SIGLA_DEPTO           VARCHAR2(5),
 CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (COD_DEPTO)
);

COMMENT ON TABLE  T_DEPARTAMENTO IS 'TABELA DE DEPARTAMENTOS';
COMMENT ON COLUMN T_DEPARTAMENTO.COD_DEPTO IS 'CODIGO DO DEPARTAMENTO. (PK)';
COMMENT ON COLUMN T_DEPARTAMENTO.NOM_DEPTO IS 'NOME DO DEPARTAMENTO';
COMMENT ON COLUMN T_DEPARTAMENTO.SIGLA_DEPTO IS 'SIGLA DO DEPARTAMENTO';

CREATE TABLE T_FUNCIONARIO
(
 MATRIC                NUMBER(05),
 NOME                  VARCHAR2(30),
 DAT_ADMISS            DATE,
 COD_DEPTO             NUMBER(2),
 CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (MATRIC),
 CONSTRAINT FK_FUNC_DEPTO FOREIGN KEY (COD_DEPTO)
            REFERENCES T_DEPARTAMENTO (COD_DEPTO)
);

COMMENT ON TABLE  T_FUNCIONARIO IS 'TABELA DE FUNCIONARIOS';
COMMENT ON COLUMN T_FUNCIONARIO.MATRIC IS 'MATRICULA DO FUNCIONARIO. (PK)';
COMMENT ON COLUMN T_FUNCIONARIO.NOME IS 'NOME DO FUNCIONARIO';
COMMENT ON COLUMN T_FUNCIONARIO.DAT_ADMISS IS 'DATA DE ADMISSAO DO FUNCIONARIO';
COMMENT ON COLUMN T_FUNCIONARIO.COD_DEPTO IS 'CODIGO DO DEPARTAMENTO DO FUNCIONARIO (FK T_DEPARTAMENTO)';

GRANT REFERENCES, SELECT ON T_FUNCIONARIO TO APBD20181_ARTHURV_ESTOQUE;
GRANT REFERENCES, SELECT ON T_FUNCIONARIO TO APBD20181_ARTHURV_VENDAS;
