/* ---------------------------------
   CRIANDO AS TABELAS
   --------------------------------- */

-- Conectar com o usuário ESTOQUE
CREATE TABLE T_PRODUTO
(
 COD_PRODUTO NUMBER(5),
 NOM_PRODUTO VARCHAR(30),
 CD_GRUPO_PROD NUMBER(2),
 CD_UNID_MEDIDA VARCHAR(3),
 VL_UNITARIO NUMBER(7,2),
 SALDO_ESTOQUE NUMBER(7,2),
 QTD_ESTOQ_MIN NUMBER(7,2),
 QTD_PTO_PEDIDO NUMBER(7,2),
 CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_PRODUTO),
 CONSTRAINT FK_PRODUTO_GRUPO FOREIGN KEY (CD_GRUPO_PROD)
            REFERENCES T_GRUPO_PROD (CD_GRUPO_PROD),
 CONSTRAINT FK_PRODUTO_UNID_MEDIDA FOREIGN KEY (CD_UNID_MEDIDA)
            REFERENCES T_UNIDADE_MEDIDA (CD_UNID_MEDIDA)
);

COMMENT ON TABLE  T_PRODUTO IS 'TABELA DE PRODUTOS';
COMMENT ON COLUMN T_PRODUTO.COD_PRODUTO IS 'CODIGO DO PRODUTO (PK)';
COMMENT ON COLUMN T_PRODUTO.NOM_PRODUTO IS 'NUMERO DO PRODUTO';
COMMENT ON COLUMN T_PRODUTO.CD_GRUPO_PROD IS 'CODIGO DO GRUPO DO PRODUTO(FK T_GRUPO_PROD)';
COMMENT ON COLUMN T_PRODUTO.CD_UNID_MEDIDA IS 'CODIGO DE UNIDADE DE MEDIDA (FK T_UNIDADE_MEDIDA)';
COMMENT ON COLUMN T_PRODUTO.VL_UNITARIO IS 'VALOR UNITARIO DO PRODUTO';
COMMENT ON COLUMN T_PRODUTO.SALDO_ESTOQUE IS 'SALDO DE PRODUTO EM ESTOQUE';
COMMENT ON COLUMN T_PRODUTO.QTD_ESTOQ_MIN IS 'QUANTIDADE DE ESTOQUE MINIMO';
COMMENT ON COLUMN T_PRODUTO.QTD_PTO_PEDIDO IS 'QUANTIDADE DE PONTO POR PEDIDO';

CREATE TABLE T_GRUPO_PROD
(
 CD_GRUPO_PROD NUMBER(02),
 DS_GRUPO_PROD VARCHAR(30),
 CONSTRAINT PK_GRUPO_PROD PRIMARY KEY (CD_GRUPO_PROD)
);

COMMENT ON TABLE  T_GRUPO_PROD IS 'TABELA DE GRUPO DE PRODUTO';
COMMENT ON COLUMN T_GRUPO_PROD.CD_GRUPO_PROD IS 'CODIGO DE GRUPO DO PRODUTO (PK)';
COMMENT ON COLUMN T_GRUPO_PROD.DS_GRUPO_PROD IS 'DESCRICAO DE GRUPO DO PRODUTO';

CREATE TABLE T_UNIDADE_MEDIDA
(
 CD_UNID_MEDIDA VARCHAR2(03),
 DS_UNIDADE_MEDIDA VARCHAR2(20),
 CONSTRAINT PK_UNID_MEDIDA PRIMARY KEY (CD_UNID_MEDIDA)
);

COMMENT ON TABLE  T_UNIDADE_MEDIDA IS 'TABELA DE UNIDADE DE MEDIDA';
COMMENT ON COLUMN T_UNIDADE_MEDIDA.CD_UNIDADE_MEDIDA IS 'CODIGO DE UNIDADE DE MEDIDA (PK)';
COMMENT ON COLUMN T_UNIDADE_MEDIDA.DS_UNIDADE_MEDIDA IS 'DESCRICAO DE UNIDADE DE MEDIDA';

CREATE TABLE T_MOV_PRODUTO
(
 COD_PRODUTO NUMBER(05),
 NUM_MOVIM   NUMBER(05),
 DAT_MOVIM   DATE,
 TIP_MOVIM   CHAR(01),
 QTD_MOVIM   NUMBER(03),
 MATR_FUNC_MOV NUMBER(05),
 CONSTRAINT PK_MOV_PRODUTO PRIMARY KEY (COD_PRODUTO,NUM_MOVIM),
 CONSTRAINT FK_MOV_PRODUTO_PRODUTO FOREIGN KEY (COD_PRODUTO)
            REFERENCES T_PRODUTO (COD_PRODUTO),
 CONSTRAINT FK_MOV_PRODUTO_FUNC FOREIGN KEY (MATR_FUNC_MOV),
            REFERENCES APBD20181_ARTHURV_FOLHA.T_FUNCIONARIO (MATRIC),
);

COMMENT ON TABLE  T_MOV_PRODUTO IS 'TABELA DE MOVIMENTO DE PRODUTO';
COMMENT ON COLUMN T_MOV_PRODUTO.COD_PRODUTO IS 'CODIGO DE DE PRODUTO (PK)(FK T_PRODUTO)';
COMMENT ON COLUMN T_MOV_PRODUTO.NUM_MOVIM IS 'NUMERO DE MOVIMENTO (PK)';
COMMENT ON COLUMN T_MOV_PRODUTO.DAT_MOVIM IS 'DATA DO MOVIMENTO';
COMMENT ON COLUMN T_MOV_PRODUTO.TIP_MOVIM IS 'TIPO DO MOVIMENTO';
COMMENT ON COLUMN T_MOV_PRODUTO.QTD_MOVIM IS 'QUANTIDADE DE PRODUTO';
COMMENT ON COLUMN T_MOV_PRODUTO.MATRIC_FUNC_MOV IS 'MATRICULA DO FUNCIONARIO DA MOVIMENTACAO (FK T_FUNCIONARIO)';


GRANT REFERENCES, SELECT ON T_PRODUTO TO APBD20181_ARTHURV_VENDAS;