/* ---------------------------------
   CRIANDO AS TABELAS
   --------------------------------- */
-- Conectar ao usuário VENDAS
CREATE TABLE T_CLIENTE
(
 COD_CLIENTE      NUMBER(5),
 NOME_CLIENTE     VARCHAR2(30),
 CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE)
);

COMMENT ON TABLE  T_CLIENTE IS 'TABELA DE CLIENTES';
COMMENT ON COLUMN T_CLIENTE.COD_CLIENTE IS 'CODIGO DO CLIENTE (PK)';
COMMENT ON COLUMN T_CLIENTE.NOME_CLIENTE IS 'NOME DO CLIENTE';

CREATE TABLE T_NOTA_FISCAL
(
 NUM_NF      NUMBER(7),
 DATA_NF     DATE,
 COD_CLIENTE NUMBER(5),
 MATR_FUNC_EMI NUMBER(5),
 CONSTRAINT PK_NOTA_FISCAL PRIMARY KEY (NUM_NF),
 CONSTRAINT FK_NF_CLIENTE FOREIGN KEY (COD_CLIENTE)
            REFERENCES T_CLIENTE (COD_CLIENTE),
 CONSTRAINT FK_NF_FUNC FOREIGN KEY (MATR_FUNC_EMI)
            REFERENCES APBD20181_ARTHURV_FOLHA.T_FUNCIONARIO (MATRIC)
);

COMMENT ON TABLE  T_NOTA_FISCAL IS 'TABELA DE NOTAS FISCAIS';
COMMENT ON COLUMN T_NOTA_FISCAL.NUM_NF IS 'NUMERO DA NOTA FISCAL. (PK)';
COMMENT ON COLUMN T_NOTA_FISCAL.DATA_NF IS 'DATA DA EMISSAO DA NOTA FISCAL';
COMMENT ON COLUMN T_NOTA_FISCAL.COD_CLIENTE IS 'CODIGO DO CLIENTE (FK T_CLIENTE)';
COMMENT ON COLUMN T_NOTA_FISCAL.MATR_FUNC_EMI IS 'MATRICULA DO FUNCIONARIO QUE EMITIU A NOTA FISCAL (FK T_FUNCIONARIO)';

CREATE TABLE T_ITEM_NF
(
 NUM_NF      NUMBER(7),
 COD_PRODUTO NUMBER(5),
 QTDE        NUMBER(9,2),
 VL_UNITARIO NUMBER(9,2),
 CONSTRAINT PK_ITENS_NF PRIMARY KEY (NUM_NF, COD_PRODUTO),
 CONSTRAINT FK_ITEMNF_NF FOREIGN KEY (NUM_NF)
            REFERENCES T_NOTA_FISCAL (NUM_NF),
 CONSTRAINT FK_ITEMNF_PRODUTO FOREIGN KEY (COD_PRODUTO)
            REFERENCES APBD20181_ARTHURV_ESTOQUE.x'T_PRODUTO (COD_PRODUTO)
);

COMMENT ON TABLE  T_ITEM_NF IS 'TABELA DE ITENS DA NOTA FISCAL';
COMMENT ON COLUMN T_ITEM_NF.NUM_NF IS 'NUMERO DA NOTA FISCAL. (PK)(FK_ T_NOTA_FISCAL)';
COMMENT ON COLUMN T_ITEM_NF.COD_PRODUTO IS 'CODIGO DO PRODUTO (PK)(FK T_PRODUTO)';
COMMENT ON COLUMN T_ITEM_NF.QTDE IS 'QUANTIDADE DO PRODUTO';
COMMENT ON COLUMN T_ITEM_NF.VL_UNITARIO IS 'VALOR DA UNIDADE DO PRODUTO';
