/* ---------------------------------
   CRIANDO AS TABELAS
   --------------------------------- */

-- Conectar com o usuário FOLHA
CREATE TABLE T_DEPARTAMENTO
(
 COD_DEPTO             NUMBER(2),
 NOM_DEPTO             VARCHAR2(30),
 SIGLA_DEPTO           VARCHAR2(5),
 CONSTRAINT PK_DEPTO PRIMARY KEY (COD_DEPTO)
);

COMMENT ON TABLE  T_DEPARTAMENTO IS 'TABELA DE DEPARTAMENTOS';
COMMENT ON COLUMN T_DEPARTAMENTO.COD_DEPTO IS 'CODIGO DO DEPARTAMENTO. (PK)';
COMMENT ON COLUMN T_DEPARTAMENTO.NOM_DEPTO IS 'NOME DO DEPARTAMENTO';
COMMENT ON COLUMN T_DEPARTAMENTO.SIGLA_DEPTO IS 'SIGLA DO DEPARTAMENTO';

CREATE TABLE T_FUNCIONARIO
(
 MATRIC                NUMBER(05),
 NOME                  VARCHAR2(30),
 DAT_ADMISS            DATE,
 COD_DEPTO             NUMBER(2),
 CONSTRAINT PK_FUNC PRIMARY KEY (MATRIC),
 CONSTRAINT FK_FUNC_DEPTO FOREIGN KEY (COD_DEPTO)
            REFERENCES T_DEPARTAMENTO (COD_DEPTO)
);

COMMENT ON TABLE  T_FUNCIONARIO IS 'TABELA DE FUNCIONARIOS';
COMMENT ON COLUMN T_FUNCIONARIO.MATRIC IS 'MATRICULA DO FUNCIONARIO. (PK)';
COMMENT ON COLUMN T_FUNCIONARIO.NOME IS 'NOME DO FUNCIONARIO';
COMMENT ON COLUMN T_FUNCIONARIO.DAT_ADMISS IS 'DATA DE ADMISSAO DO FUNCIONARIO';
COMMENT ON COLUMN T_FUNCIONARIO.COD_DEPTO IS 'CODIGO DO DEPARTAMENTO DO FUNCIONARIO (FK T_DEPARTAMENTO)';

GRANT REFERENCES, SELECT ON T_FUNCIONARIO TO ESTOQUE;
GRANT REFERENCES, SELECT ON T_FUNCIONARIO TO VENDAS;

-- Conectar ao usuário VENDAS

CREATE TABLE T_CLIENTE
(
 COD_CLIENTE      NUMBER(5),
 NOME_CLIENTE     VARCHAR2(30),
 CONSTRAINT PK_CLIENTE PRIMARY KEY (COD_CLIENTE)
);

COMMENT ON TABLE  T_CLIENTE IS 'TABELA DE CLIENTES';
COMMENT ON COLUMN T_CLIENTE.COD_CLIENTE IS 'CODIGO DO CLIENTE (PK)';
COMMENT ON COLUMN T_CLIENTE.NOME_CLIENTE IS 'NOME DO CLIENTE';

CREATE TABLE T_NOTA_FISCAL
(
 NUM_NF      NUMBER(7),
 DATA_NF     DATE,
 COD_CLIENTE NUMBER(5),
 MATR_FUNC_EMI NUMBER(5),
 CONSTRAINT PK_NF PRIMARY KEY (NUM_NF),
 CONSTRAINT FK_NF_CLIENTE FOREIGN KEY (COD_CLIENTE)
            REFERENCES T_CLIENTE (COD_CLIENTE),
 CONSTRAINT FK_NF_FUNC FOREIGN KEY (MATR_FUNC_EMI)
            REFERENCES FOLHA.T_FUNCIONARIO (MATRIC)
);

COMMENT ON TABLE  T_NOTA_FISCAL IS 'TABELA DE NOTAS FISCAIS';
COMMENT ON COLUMN T_NOTA_FISCAL.NUM_NF IS 'NUMERO DA NOTA FISCAL. (PK)';
COMMENT ON COLUMN T_NOTA_FISCAL.DATA_NF IS 'DATA DA EMISSAO DA NOTA FISCAL';
COMMENT ON COLUMN T_NOTA_FISCAL.COD_CLIENTE IS 'CODIGO DO CLIENTE (FK T_CLIENTE)';
COMMENT ON COLUMN T_NOTA_FISCAL.MATR_FUNC_EMI IS 'MATRICULA DO FUNCIONARIO QUE EMITIU A NOTA FISCAL (FK T_FUNCIONARIO)';

CREATE TABLE T_ITEM_NF
(
 NUM_NF      NUMBER(7),
 COD_PRODUTO NUMBER(5),
 QTDE        NUMBER(9,2),
 VL_UNITARIO NUMBER(9,2),
 CONSTRAINT PK_ITEMNF PRIMARY KEY (NUM_NF),
 CONSTRAINT FK_ITEMNF_NF FOREIGN KEY (NUM_NF)
            REFERENCES T_NOTA_FISCAL (NUM_NF),
 CONSTRAINT PK_ITEMNF PRIMARY KEY (COD_PRODUTO),
 CONSTRAINT FK_ITEMNF_PROD FOREIGN KEY (COD_PRODUTO)
            REFERENCES T_PRODUTO (COD_PRODUTO)
);

COMMENT ON TABLE  T_ITEM_NF IS 'TABELA DE ITENS DA NOTA FISCAL';
COMMENT ON COLUMN T_ITEM_NF.NUM_NF IS 'NUMERO DA NOTA FISCAL. (PK)(FK_ T_NOTA_FISCAL)';
COMMENT ON COLUMN T_ITEM_NF.COD_PRODUTO IS 'CODIGO DO PRODUTO (PK)(FK T_PRODUTO)';
COMMENT ON COLUMN T_ITEM_NF.QTDE IS 'QUANTIDADE DO PRODUTO';
COMMENT ON COLUMN T_ITEM_NF.VL_UNITARIO IS 'VALOR DA UNIDADE DO PRODUTO';

CREATE TABLE T_PRODUTO
(
 COD_PRODUTO NUMBER(5),
 NOM_PRODUTO VARCHAR(30),
 CD_GRUPO_PROD NUMBER(02),
 CD_UNID_MEDIDA VARCHAR(03),
 VL_UNITARIO NUMBER(07,2),
 SALDO_ESTOQUE NUMBER(07,2),
 QTD_ESTOQ_MIN NUMBER(07,2),
 QTD_PTO_PEDIDO NUMBER(07,2),
 CONSTRAINT PK_PRODUTO PRIMARY KEY (COD_PRODUTO),
 CONSTRAINT FK_PRODUTO_GRUPROD FOREIGN KEY (CD_GRUPO_PROD)
            REFERENCES T_GRUPO_PROD (CD_GRUPO_PROD),
 CONSTRAINT FK_PRODUTO_UNIDMEDIDADE FOREIGN KEY (CD_UNID_MEDIDA)
            REFERENCES T_UNIDADE_MEDIDA (CD_UNID_MEDIDA)
);

COMMENT ON TABLE  T_PRODUTO IS 'TABELA DE PRODUTOS';
COMMENT ON COLUMN T_PRODUTO.COD_PRODUTO IS 'CODIGO DO PRODUTO (PK)';
COMMENT ON COLUMN T_PRODUTO.NOM_PRODUTO IS 'NUMERO DO PRODUTO';
COMMENT ON COLUMN T_PRODUTO.CD_GRUPO_PROD IS 'CODIGO DO GRUPO DO PRODUTO(FK T_GRUPO_PROD)';
COMMENT ON COLUMN T_PRODUTO.CD_UNID_MEDIDA IS 'CODIGO DE UNIDADE DE MEDIDA (FK T_UNIDADE_MEDIDA)';
COMMENT ON COLUMN T_PRODUTO.VL_UNITARIO IS 'VALOR UNITARIO DO PRODUTO';
COMMENT ON COLUMN T_PRODUTO.SALDO_ESTOQUE IS 'SALDO DE PRODUTO EM ESTOQUE';
COMMENT ON COLUMN T_PRODUTO.QTD_ESTOQ_MIN IS 'QUANTIDADE DE ESTOQUE MINIMO';
COMMENT ON COLUMN T_PRODUTO.QTD_PTO_PEDIDO IS 'QUANTIDADE DE PONTO POR PEDIDO';

CREATE TABLE T_GRUPO_PROD
(
 CD_GRUPO_PROD NUMBER(02),
 DS_GRUPO_PROD VARCHAR(30),
 CONSTRAINT PK_GRUPO_PROD PRIMARY KEY (CD_GRUPO_PROD),
);

COMMENT ON TABLE  T_GRUPO_PROD IS 'TABELA DE GRUPO DE PRODUTO';
COMMENT ON COLUMN T_GRUPO_PROD.CD_GRUPO_PROD IS 'CODIGO DE GRUPO DO PRODUTO (PK)';
COMMENT ON COLUMN T_GRUPO_PROD.DS_GRUPO_PROD IS 'DESCRICAO DE GRUPO DO PRODUTO';

CREATE TABLE T_UNIDADE_MEDIDA
(
 CD_UNID_MEDIDA VARCHAR2(03),
 DS_UNIDADE_MEDIDA VARCHAR2(20),
 CONSTRAINT PK_UNIDADE_MEDIDA PRIMARY KEY (CD_UNID_MEDIDA),
);

COMMENT ON TABLE  T_UNIDADE_MEDIDA IS 'TABELA DE UNIDADE DE MEDIDA';
COMMENT ON COLUMN T_UNIDADE_MEDIDA.CD_UNIDADE_MEDIDA IS 'CODIGO DE UNIDADE DE MEDIDA (PK)';
COMMENT ON COLUMN T_UNIDADE_MEDIDA.DS_UNIDADE_MEDIDA IS 'DESCRICAO DE UNIDADE DE MEDIDA';
